"""
test.py — Evaluation of the trained BiGRU DeviationClassifier on the held-out test split.
Owner: Member 3

Reports per-class accuracy, macro F1, weighted F1, and per-body-part confusion matrices.
Also computes a fixed-threshold baseline for comparison.

Launch via main.py:
    python main.py test --test-dir data/test/ \
                        --checkpoint checkpoints/best_model.pt \
                        --out results/test_metrics.json
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import torch
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    f1_score,
)
from torch.utils.data import DataLoader

from dataset import DanceDeviationDataset, collate_fn, PART_ORDER, N_PARTS
from model import load_checkpoint
from scoring import THRESHOLD_GOOD, THRESHOLD_MODERATE

CLASS_NAMES = ["good", "moderate", "off"]


def evaluate(
    test_dir: str,
    checkpoint_path: str,
    out_path: str = "results/test_metrics.json",
    device: str | None = None,
) -> dict:
    """Run evaluation on the test split and save metrics to JSON.

    Returns the metrics dictionary.
    """
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"[test] Device: {device}")

    # Load data
    test_ds = DanceDeviationDataset(test_dir)
    loader  = DataLoader(test_ds, batch_size=16, shuffle=False,
                         collate_fn=collate_fn, num_workers=2)
    print(f"[test] Test samples: {len(test_ds)}")

    # Load model
    model, ckpt_meta = load_checkpoint(checkpoint_path, device=device)
    epoch  = ckpt_meta.get('epoch', '?')
    val_f1 = ckpt_meta.get('val_f1')
    f1_str = f"{val_f1:.4f}" if isinstance(val_f1, float) else "?"
    print(f"[test] Loaded checkpoint from epoch {epoch} (val_f1={f1_str})")

    # Collect predictions
    all_preds   = []   # list of (N,) tensors
    all_targets = []

    model.eval()
    with torch.no_grad():
        for features, labels, lengths in loader:
            features = features.to(device)
            logits   = model(features)         # (B, T_max, 6, 3)
            preds    = logits.argmax(dim=-1)   # (B, T_max, 6)

            mask = labels != -1
            all_preds.append(preds[mask].cpu().numpy())
            all_targets.append(labels[mask].cpu().numpy())

    preds_flat   = np.concatenate(all_preds)
    targets_flat = np.concatenate(all_targets)

    # ---- Overall metrics ----
    print("\n=== Overall Classification Report ===")
    report_str = classification_report(targets_flat, preds_flat,
                                       target_names=CLASS_NAMES)
    print(report_str)

    macro_f1    = f1_score(targets_flat, preds_flat, average="macro")
    weighted_f1 = f1_score(targets_flat, preds_flat, average="weighted")
    accuracy    = float((preds_flat == targets_flat).mean())

    # ---- Per-body-part metrics ----
    # Reload raw predictions grouped by part index
    all_preds_by_part   = [[] for _ in range(N_PARTS)]
    all_targets_by_part = [[] for _ in range(N_PARTS)]

    with torch.no_grad():
        for features, labels, lengths in loader:
            features = features.to(device)
            logits   = model(features)         # (B, T_max, 6, 3)
            preds_t  = logits.argmax(dim=-1)   # (B, T_max, 6)
            for p in range(N_PARTS):
                mask = labels[:, :, p] != -1
                all_preds_by_part[p].append(preds_t[:, :, p][mask].cpu().numpy())
                all_targets_by_part[p].append(labels[:, :, p][mask].cpu().numpy())

    part_metrics = {}
    print("\n=== Per-Body-Part Metrics ===")
    for p, part in enumerate(PART_ORDER):
        p_preds   = np.concatenate(all_preds_by_part[p])
        p_targets = np.concatenate(all_targets_by_part[p])
        p_f1      = f1_score(p_targets, p_preds, average="macro")
        p_cm      = confusion_matrix(p_targets, p_preds, labels=[0, 1, 2]).tolist()
        p_acc     = float((p_preds == p_targets).mean())
        part_metrics[part] = {"macro_f1": round(p_f1, 4),
                              "accuracy": round(p_acc, 4),
                              "confusion_matrix": p_cm}
        print(f"  {part:12s}  F1={p_f1:.4f}  Acc={p_acc:.4f}")

    # ---- Fixed-threshold baseline ----
    # The labels themselves were generated by the threshold, so baseline = perfect
    # but we report it to show the model can match or exceed it on noisy real data
    print("\n=== Threshold Baseline (on test features) ===")
    # feature col +3 of each part = mean_joint_err → use it for threshold label
    baseline_preds = []
    baseline_targets = []
    for features, labels, lengths in loader:
        B, T, _ = features.shape
        for b in range(B):
            for t in range(T):
                for p in range(N_PARTS):
                    lbl = labels[b, t, p].item()
                    if lbl == -1:
                        continue
                    mean_err = features[b, t, p * 4 + 3].item()
                    if mean_err >= THRESHOLD_MODERATE:
                        base_lbl = 2
                    elif mean_err >= THRESHOLD_GOOD:
                        base_lbl = 1
                    else:
                        base_lbl = 0
                    baseline_preds.append(base_lbl)
                    baseline_targets.append(lbl)

    base_f1  = f1_score(baseline_targets, baseline_preds, average="macro")
    base_acc = float((np.array(baseline_preds) == np.array(baseline_targets)).mean())
    print(f"  Threshold baseline — macro F1: {base_f1:.4f}  Acc: {base_acc:.4f}")

    # ---- Save results ----
    metrics = {
        "overall": {
            "accuracy":    round(accuracy,    4),
            "macro_f1":    round(macro_f1,    4),
            "weighted_f1": round(weighted_f1, 4),
        },
        "per_part": part_metrics,
        "baseline": {
            "macro_f1": round(base_f1, 4),
            "accuracy": round(base_acc, 4),
        },
        "checkpoint_meta": {k: str(v) for k, v in ckpt_meta.items()},
    }

    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text(json.dumps(metrics, indent=2))
    print(f"\n[test] Metrics saved → {out_path}")
    return metrics
